### PR TITLE
Add AWS_SESSION_TOKEN, so we can use leftovers with aws-vault

### PR DESCRIPTION
**Pull request by pccowboy**

### CODE REVIEW

**Comment by genevieve** [comment]
Hey @pccowboy! 

I think there's an acceptance test that needs to be updated to accept this parameter (empty or otherwise): https://github.com/genevieve/leftovers/blob/master/acceptance/aws_test.go#L38

Otherwise this looks good to go and some teams will need to be updated since this introduces a breaking change in the library. 

cc @nmahoney-pivotal

**Comment by pccowboy** [comment]
Hi @genevieve - will this be sufficient for the test, since it is an optional field?
```
	sessionToken := os.Getenv("BBL_AWS_SESSION_TOKEN")
	Expect(sessionToken).To(Equal(""), "Optional field")

```

**Comment by genevieve** [comment]
I think if you just pass an empty string into the constructor for that new field it should be okay.

**Comment by pccowboy** [comment]
@genevieve Hopefully this updates the acceptance tests in a way that works.

**Comment by genevieve** [comment]
Thanks @pccowboy!

**Comment by genevieve** [comment]
There's another commit blocking a release of leftovers in CI right now, but once that's through, this will be in the next release.

**Pull request merged**
