### PR TITLE
Update to ginkgo 2

### PR DESCRIPTION
**Pull request by Alphasite**
Update from v1 to ginkgo v2

### CODE REVIEW

**Comment by genevieve** [comment]
There are a few other places where ginkgo v1 are referenced so I'll make some edits to this MR.

**Comment by genevieve** [comment]
@Alphasite What happens when you run `ginkgo -r .` against these changes?

**Comment by genevieve** [comment]
It looks like this MR might have removed all the imported ginkgo lines instead of updating them to v2 so I opened https://github.com/genevieve/leftovers/pull/112 but please let me know if I'm missing something.

**Comment by Alphasite** [comment]
Ah sorry, i think i messed up when i was trying to split it out into separate MRs. Your PR looks great though!

**Comment by genevieve** [comment]
Ok great, closing in favor of #112

**Pull request closed without merging**
